<?php
// This file generated by Propel 1.6.4-dev convert-conf target
// from XML runtime conf file /home/oz/workspace/blank-project/source/application/config/propel/runtime-conf.xml
$conf = array (
  'generator_version' => '1.6.4-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'generated-classmap.php');
return $conf;